CREATE TABLE BRANCH(
    BNAME VARCHAR2(20) PRIMARY KEY,
    CITY VARCHAR2(30) NOT NULL
);


INSERT INTO BRANCH(BNAME, CITY) VALUES 
   ('VRCE','NAGPUR'),('AJNI','NAGPUR'),('KAROLBAGH','DELHI'),
   ('CHANDNI','DELHI'),('DHARAMPETH','NAGPUR'),('MG ROAD','BANGALORE'),
   ('ANDHERI','BOMBAY'),('NEHRU PALACE','DELHI'),('POWAI','BOMBAY');


CREATE TABLE CUSTOMER(
    CNAME VARCHAR2(15) PRIMARY KEY, 
    CITY VARCHAR2(20) NOT NULL
);

INSERT INTO `CUSTOMER`(`CNAME`, `CITY`) VALUES ('ANIL','CULCUTTA'),
   ('SUNIL','DELHI'),('MEHUL','BARODA'),('MANDAR','PANTA'),
   ('MADHURI','NAGPUR'),('PRAMOD','NAGPUR'),('SANDIP','SURAT'),
   ('SHIVANI','BOMBAY'),('KRANTI','BOMBAY'),('NAREN','BOMBAY');